Repository codezoned/PsipherBackend, pull requests merged in 2020-07, with the labels that each got.

#1 Added new Api, defined new model also added new permission to lambda and setup logging
  pom.xml
  src/main/java/com/psipher/application/actions/UserDetailsOperations.java
  src/main/java/com/psipher/application/actions/UserDetailsOperationsImpl.java
  src/main/java/com/psipher/application/api/SaveDetails.java
  src/main/java/com/psipher/application/config/ApplicationContext.java
  src/main/java/com/psipher/application/ddbmodel/UserAccountDDBModel.java
  src/main/java/com/psipher/application/ddbmodel/UserDDBModel.java
  src/main/java/com/psipher/application/ddbmodel/WebsiteDDBModel.java
  src/main/java/com/psipher/application/model/SaveDetailsInput.java
  src/main/java/com/psipher/application/model/SaveDetailsOutput.java
  src/main/resources/log4j2.xml
  template.yml
Labels: enhancement

#3 Upgraded log4j to avoid security risk
  pom.xml
Labels: security-risk

#5 Fixed DDB model and used @component for binding of savedetailoperations
  src/main/java/com/psipher/application/actions/UserDetailsOperationsImpl.java
  src/main/java/com/psipher/application/config/ApplicationContext.java
  src/main/java/com/psipher/application/ddbmodel/UserAccountDDBModel.java
Labels: bug

#8 High Level Design of Psipher.
  HLD.md
  PsipherComplete.png
  PsipherSwagger.png
  README.md
Labels: enhancement

#9 implemented viewDetails api
  src/main/java/com/psipher/application/actions/UserDetailsOperations.java
  src/main/java/com/psipher/application/actions/UserDetailsOperationsImpl.java
  src/main/java/com/psipher/application/api/UserPing.java
  src/main/java/com/psipher/application/api/ViewDetails.java
  src/main/java/com/psipher/application/ddbmodel/WebsiteDDBModel.java
  src/main/java/com/psipher/application/exceptions/DDBException.java
  src/main/java/com/psipher/application/model/ViewDetailsOutput.java
Labels: enhancement

#12 Implemented Delete Domain API
  src/main/java/com/psipher/application/actions/UserDetailsOperations.java
  src/main/java/com/psipher/application/actions/UserDetailsOperationsImpl.java
  src/main/java/com/psipher/application/api/DeleteDomain.java
  src/main/java/com/psipher/application/model/DeleteDomainInput.java
  src/main/java/com/psipher/application/model/DeleteDomainOutput.java
Labels: enhancement

#13 Added DeleteUserID API
  src/main/java/com/psipher/application/actions/UserDetailsOperations.java
  src/main/java/com/psipher/application/actions/UserDetailsOperationsImpl.java
  src/main/java/com/psipher/application/api/DeleteUser.java
  src/main/java/com/psipher/application/model/DeleteUserInput.java
  src/main/java/com/psipher/application/model/DeleteUserOutput.java
Labels: enhancement

#14 New DeleteUserAccount API
  src/main/java/com/psipher/application/actions/UserDetailsOperations.java
  src/main/java/com/psipher/application/actions/UserDetailsOperationsImpl.java
  src/main/java/com/psipher/application/api/DeleteUserAccount.java
  src/main/java/com/psipher/application/model/DeleteUserAccountInput.java
  src/main/java/com/psipher/application/model/DeleteUserAccountOutput.java
Labels: enhancement

#16 Password Generation API
  pom.xml
  src/main/java/com/psipher/application/actions/GeneratePasswordOperations.java
  src/main/java/com/psipher/application/actions/GeneratePasswordOperationsImpl.java
  src/main/java/com/psipher/application/api/GeneratePassword.java
  src/main/java/com/psipher/application/model/GeneratePasswordOutput.java
Labels: enhancement
